FROM almalinux
LABEL AUTHOR="DD" \
      COURSE = "DOCKER" \
      DURATION = "25Hrs"


# $docker build -t DDRaja/label:v1  # to build docker image
# $docker images
# $docker inspect label_dockerimage_id
# $docker images --filter "label-Author=DD" ## main advantage is to filter using labels
